#!/bin/sh
echo "Deleting buid..."
rm -fR build
echo "Making build..."
mkdir build
echo "Reconfigure..."
autoreconf --install --force
cd build
echo "Configure on dir $1"
../configure --prefix=$1
echo "make..."
make
